### ISSUE TITLE
Link project board to repo

### ISSUE THREAD

**Issue by catw101** [ErickCif/queue-r#8]

**Comment by ErickCif** [comment]
On the GitHub guide for doing so, it says that I should have a 'projects' tab on the main page of my repo but I don't seem to have one, is there something I'm doing wrong here? Couldn't find anything on missing projects tab online...

**Comment by catw101** [comment]
You should be able to turn on "Projects" in your repo settings (it'll be under "Features")

**Comment by ErickCif** [comment]
Thank you!
